
#Mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/book_ex?useUnicode=true&charaterEncoding=utf-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8
    username: root
    password: 505050
    driverClassName: com.mysql.cj.jdbc.Driver

  #Jpa Option
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: false
    show-sql: true
